### ISSUE TITLE
Is this module available in Ansible Galaxy central?

### ISSUE THREAD

**Issue by jjzazuet** [mrlesmithjr/ansible-change-hostname#3]
Thanks for this awesome module. Just wondering if it's possible to reference `ansible install` without pointing at the Github repository location.

Thanks again!

**Comment by mrlesmithjr** [comment]
@jjzazuet Are you referring to https://galaxy.ansible.com/mrlesmithjr/change-hostname/ ?

**Comment by jjzazuet** [comment]
@mrlesmithjr oh ok, I see. I was using "change hosts" term in Ansible Galaxy, which did not bring up this playbook. Found it now. Thanks!

**Comment by mrlesmithjr** [comment]
@jjzazuet Perfect.
